ros_mqtt_bridge:
  ros__parameters:

    broker:
      host: 155.98.37.82
      port: 31883        # Port-forwardolt Mosquitto port

    client:
      id: "ros2_mqtt_client"

    bridge:

      # ROS → MQTT irány: robot állapotát küldjük
      ros2mqtt:
        ros_topics:
          - "/robot_state"
        "/robot_state":
          mqtt_topic: "robot/state"
          primitive: true
          ros_type: "std_msgs/msg/String"

      # MQTT → ROS irány: parancs jön MQTT-ről
      mqtt2ros:
        mqtt_topics:
          - "robot/cmd"
        "robot/cmd":
          ros_topic: "/robot/cmd"
          ros_type: "std_msgs/msg/String"
          primitive: true
